language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dreshik/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dreshik/docker-react npm run test